# Generated by Django 3.2.8 on 2022-07-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20220701_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='subject',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='FeedbackSubject',
        ),
    ]
